name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Install (no deps required; fallback to npm i)
        run: npm ci || npm i

      - name: Normalize CSV and build manifest
        run: npm run csv:normalize

      - name: Remove non-essential data files from artifact
        run: |
          rm -f SWC_youtube_project/videos.csv || true
          rm -f SWC_youtube_project/sheet.csv || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
